// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IIconoir:bicycle': typeof import('~icons/iconoir/bicycle')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export { }
